name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version

    - name: Run check
      run: cargo check --workspace

    - name: Run test (Verbose)
      run: cargo test --verbose
